Switch to github-actions-deploy-aur
This will mean different history between Github and AUR, but it will
also save the repo from subtree hell, so it's worth it.

diff --git a/.github/workflows/update-package.yml b/.github/workflows/update-package.yml
--- a/.github/workflows/update-package.yml
+++ b/.github/workflows/update-package.yml
@@ -5,23 +5,32 @@ on:
         type: string
         description: Package name
         required: true
-      check-script:
+      new-pkgver:
         type: string
-        description: |
-          Script to check for a new version of the package.
-          Supported outputs are new_pkgver and new_pkgrel.
-        required: true
+        required: false
+      new-pkgrel:
+        type: string
+        required: false
+      publish-to-aur:
+        type: string
+        required: false
+        default: 'no'
 
 jobs:
-  update-insiders:
+  do:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate inputs
+        run: |
+          if [ -z "${{ inputs.new-pkgver }}" ] && [ -z "${{ inputs.new-pkgrel }}" ]; then
+            echo "::error ::new-pkgver and new-pkgrel both empty"
+            exit 1
+          fi
       - name: Clone repository
         uses: actions/checkout@v4
         with:
           ref: ${{ github.head_ref }}
           ssh-key: ${{ secrets.SSH_KEY_PRIVATE }}
-          fetch-depth: '0'
       - name: Configure SSH and git
         run: |
           mkdir ~/.ssh
@@ -49,11 +58,8 @@ jobs:
           git config --global commit.gpgsign true
           git config --global user.email "${{ secrets.GIT_EMAIL }}"
           git config --global user.name "${{ secrets.GIT_USER }}"
-      - name: Check new version
-        id: check
-        run: ${{ inputs.check-script }}
       - name: "Update checksums & .SRCINFO"
-        if: steps.check.outputs.new_pkgver != '' || steps.ucheckpdate.outputs.new_pkgrel != ''
+        if: inputs.new-pkgver != '' || inputs.new-pkgrel != ''
         id: makepkg
         uses: dcelasun/archlinux-package-action@37a7b00ba9b402edce0bf04aa82229800eec516c # 24-May-2025
         with:
@@ -61,22 +67,39 @@ jobs:
           updpkgsums: true
           srcinfo: true
           namcap: false
-          pkgver: '${{ steps.update.outputs.new_pkgver }}'
-          pkgrel: '${{ steps.update.outputs.new_pkgrel }}'
+          pkgver: '${{ inputs.new-pkgver }}'
+          pkgrel: '${{ inputs.new-pkgrel }}'
       - name: Commit changes
         if: steps.makepkg.outcome == 'success'
         id: commit
         run: |
           pkgname="${{ inputs.pkgname }}"
-          msg="Update to ${{ steps.update.outputs.new_pkgver }}"
-          if [ -z "${{ steps.update.outputs.new_pkgver }}" ]; then
-            msg="Bump pkgrel to ${{ steps.update.outputs.new_pkgrel }}"
+          msg="Update to ${{ inputs.new-pkgver }}"
+          if [ -z "${{ inputs.new-pkgver }}" ]; then
+            msg="Bump pkgrel to ${{ inputs.new-pkgrel }}"
           fi
           msg="$(printf "[$pkgname] ${msg}\n\n[skip ci]")"
+
+          # This ugliness is necessary to escape square brackets within the message
+          # See comments of https://stackoverflow.com/a/74232400/879047
+          echo "commit_msg<<EOF"$'\n'"$msg"$'\n'EOF >> $GITHUB_OUTPUT
 
           git commit -am "$msg"
           git push
       - name: Push to AUR
-        if: steps.commit.outcome == 'success'
-        run: |
-          ./aurpublish ${{ inputs.pkgname }}
+        if: steps.commit.outcome == 'success' && inputs.publish-to-aur == 'yes'
+        uses: KSXGitHub/github-actions-deploy-aur@2ac5a4c1d7035885d46b10e3193393be8460b6f1 # v4.1.1
+        with:
+          pkgname: ${{ inputs.pkgname }}
+          pkgbuild: ./${{ inputs.pkgname }}/PKGBUILD
+          assets: |
+            ./${{ inputs.pkgname }}/*
+          post_process: |
+            git config --global gpg.format ssh
+            git config --global user.signingkey ~/.ssh/aur
+            git config --global commit.gpgsign true
+          commit_username: ${{ secrets.GIT_USER }}
+          commit_email: ${{ secrets.GIT_EMAIL }}
+          ssh_private_key: ${{ secrets.SSH_KEY_PRIVATE }}
+          commit_message: ${{ steps.commit.outputs.commit_msg }}
+          ssh_keyscan_types: ed25519
diff --git a/.github/workflows/vscode-insiders.yml b/.github/workflows/vscode-insiders.yml
--- a/.github/workflows/vscode-insiders.yml
+++ b/.github/workflows/vscode-insiders.yml
@@ -15,51 +15,70 @@ on:
   schedule:
     - cron: "0 1 * * *" # 01:00 every day
 
-env:
-  FORCE_UPDATE: ${{ inputs.force-update != '' && inputs.force-update || 'yes' }}
-
 jobs:
+  setup:
+    # See link for why this is needed
+    # https://github.com/orgs/community/discussions/26671#discussioncomment-3252793
+    name: Setup
+    runs-on: ubuntu-latest
+    outputs:
+      new_pkgver: ${{ steps.pkg.outputs.new_pkgver }}
+      new_pkgrel: ${{ steps.pkg.outputs.new_pkgrel }}
+    steps:
+      - name: Clone repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+          ssh-key: ${{ secrets.SSH_KEY_PRIVATE }}
+      - name: Calculate pkgver and pkgrel
+        id: pkg
+        run: |
+          version_current=$(awk 'match($0, "^pkgver=([0-9]+)$", arr) {print arr[1]}' visual-studio-code-insiders-bin/PKGBUILD)
+          pkgrel_current=$(awk 'match($0, "^pkgrel=([0-9]+)$", arr) {print arr[1]}' visual-studio-code-insiders-bin/PKGBUILD)
+
+          if [ -z "${version_current}" ]; then
+          echo "::error ::Could not find current version"
+          exit 1
+          fi
+
+          version_x86=$(IFS='/' read -ra ADDR <<< $(curl -ILs -o /dev/null -w %{url_effective} https://update.code.visualstudio.com/latest/linux-x64/insider); echo "${ADDR[7]}" | sed 's/code-insider-x64-//g' | sed 's/.tar.gz//g' | sed 's/-/./g')
+          version_a64=$(IFS='/' read -ra ADDR <<< $(curl -ILs -o /dev/null -w %{url_effective} https://update.code.visualstudio.com/latest/linux-arm64/insider); echo "${ADDR[7]}" | sed 's/code-insider-arm64-//g' | sed 's/.tar.gz//g' | sed 's/-/./g')
+          version_a7h=$(IFS='/' read -ra ADDR <<< $(curl -ILs -o /dev/null -w %{url_effective} https://update.code.visualstudio.com/latest/linux-armhf/insider); echo "${ADDR[7]}" | sed 's/code-insider-armhf-//g' | sed 's/.tar.gz//g' | sed 's/-/./g')
+
+          version_new=""
+          if [ -n "${version_x86}" ]; then
+          version_new=$version_x86
+          elif [ -n "${version_a64}" ]; then
+          version_new=$version_a64
+          elif [ -n "${version_a7h}" ]; then
+          version_new=$version_a7h
+          fi
+
+          if [ -z "${version_new}" ]; then
+          echo "::error ::Could not find new version for any arch"
+          exit 1
+          fi
+
+          if [ "${version_current}" == "${version_new}" ]; then
+            echo "::notice ::No new version found, still at $version_current"
+            if [ "${{ github.event.inputs.force-update || 'no' }}" == 'yes' ]; then
+              pkgrel=$((pkgrel_current + 1))
+              echo "::notice ::Force update requested, bumping pkgrel to $pkgrel"
+              echo "new_pkgrel=$pkgrel" >> $GITHUB_OUTPUT
+            fi
+            exit 0
+          fi
+
+          echo "::notice ::Version changed $version_current -> $version_new"
+          echo "new_pkgver=$version_new" >> $GITHUB_OUTPUT
+          echo "new_pkgrel=1" >> $GITHUB_OUTPUT
   update-insiders:
+    name: Update package
     uses: ./.github/workflows/update-package.yml
+    needs: setup
+    secrets: inherit
     with:
       pkgname: visual-studio-code-insiders-bin
-      check-script: |
-        version_current=$(awk 'match($0, "^pkgver=([0-9]+)$", arr) {print arr[1]}' visual-studio-code-insiders-bin/PKGBUILD)
-        pkgrel_current=$(awk 'match($0, "^pkgrel=([0-9]+)$", arr) {print arr[1]}' visual-studio-code-insiders-bin/PKGBUILD)
-
-        if [ -z "${version_current}" ]; then
-        echo "::error ::Could not find current version"
-        exit 1
-        fi
-
-        version_x86=$(IFS='/' read -ra ADDR <<< $(curl -ILs -o /dev/null -w %{url_effective} https://update.code.visualstudio.com/latest/linux-x64/insider); echo "${ADDR[7]}" | sed 's/code-insider-x64-//g' | sed 's/.tar.gz//g' | sed 's/-/./g')
-        version_a64=$(IFS='/' read -ra ADDR <<< $(curl -ILs -o /dev/null -w %{url_effective} https://update.code.visualstudio.com/latest/linux-arm64/insider); echo "${ADDR[7]}" | sed 's/code-insider-arm64-//g' | sed 's/.tar.gz//g' | sed 's/-/./g')
-        version_a7h=$(IFS='/' read -ra ADDR <<< $(curl -ILs -o /dev/null -w %{url_effective} https://update.code.visualstudio.com/latest/linux-armhf/insider); echo "${ADDR[7]}" | sed 's/code-insider-armhf-//g' | sed 's/.tar.gz//g' | sed 's/-/./g')
-
-        version_new=""
-        if [ -n "${version_x86}" ]; then
-        version_new=$version_x86
-        elif [ -n "${version_a64}" ]; then
-        version_new=$version_a64
-        elif [ -n "${version_a7h}" ]; then
-        version_new=$version_a7h
-        fi
-
-        if [ -z "${version_new}" ]; then
-        echo "::error ::Could not find new version for any arch"
-        exit 1
-        fi
-
-        if [ "${version_current}" == "${version_new}" ]; then
-          echo "::notice ::No new version found, still at $version_current"
-          if [ "${{ env.FORCE_UPDATE }}" == 'yes' ]; then
-            pkgrel=$((pkgrel_current + 1))
-            echo "::notice ::Force update requested, bumping pkgrel to $pkgrel"
-            echo "new_pkgrel=$pkgrel" >> $GITHUB_OUTPUT
-          fi
-          exit 0
-        fi
-
-        echo "::notice ::Version changed $version_current -> $version_new"
-        echo "new_version=$version_new" >> $GITHUB_OUTPUT
-        echo "new_pkgrel=1" >> $GITHUB_OUTPUT
+      new-pkgver: ${{ needs.setup.outputs.new_pkgver }}
+      new-pkgrel: ${{ needs.setup.outputs.new_pkgrel }}
+      publish-to-aur: 'yes'
